name: daily_collector
on:
  schedule:
    - cron: '15 0 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run collector
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: python -m src.ghp_collector
