name: monthly_report

on:
  schedule:
    - cron: '15 0 1 * *'        # 毎月 09:15 JST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Generate & Mail report
        env:
          DB_URL:     ${{ secrets.DB_URL }}
          GMAIL_USER: ${{ secrets.ghp.research.rx@gmail.com  }}
          GMAIL_PASS: ${{ secrets.gpmiggaffkfjsimx }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}   # GPT 要約を使う場合だけ
        run: python -m src.ghp_report
